# Generated by Django 5.1.8 on 2025-05-04 10:01

import lifetracker.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=lifetracker.users.models.get_avatar_path, verbose_name='Avatar'),
        ),
    ]
