# Generated by Django 5.1.8 on 2025-05-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
