# Generated by Django 5.1.8 on 2025-05-06 10:28

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-recorded_at', '-created_at'], 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.RemoveConstraint(
            model_name='diary',
            name='unique_diary_entry_per_day',
        ),
        migrations.AddField(
            model_name='diary',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diary',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('user', 'recorded_at'), name='unique_diary_entry_per_datetime'),
        ),
    ]
