# Generated by Django 5.1.8 on 2025-05-06 10:28

from django.db import migrations
from django.utils import timezone
from datetime import datetime, time


def populate_recorded_at(apps, schema_editor):
    """
    Populate the recorded_at field with a datetime from the entry_date field.
    For each entry, we'll use the entry_date at midnight (start of day).
    """
    Diary = apps.get_model('diary', 'Diary')
    
    for diary in Diary.objects.all():
        if diary.entry_date and not diary.recorded_at:
            # Convert date to datetime at noon
            noon_time = time(12, 0, 0)  # 12:00:00
            recorded_datetime = datetime.combine(diary.entry_date, noon_time)
            
            # Make it timezone aware
            diary.recorded_at = timezone.make_aware(recorded_datetime)
            diary.save(update_fields=['recorded_at'])


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - populate entry_date from recorded_at
    """
    Diary = apps.get_model('diary', 'Diary')
    
    for diary in Diary.objects.all():
        if diary.recorded_at and not diary.entry_date:
            diary.entry_date = diary.recorded_at.date()
            diary.save(update_fields=['entry_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diary_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_recorded_at, reverse_migration),
    ]
