# Generated by Django 5.1.8 on 2025-05-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_populate_recorded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='entry_date',
        ),
    ]
