# Generated by Django 5.1.8 on 2025-05-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_entry_date'),
        ('diary', 'consolidate_diaries'),
    ]

    operations = [
    ]
