# Generated by Django 5.1.8 on 2025-05-09 00:13

import django.db.models.deletion
import django.utils.timezone
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_tag_diary_tags_tag_unique_tag_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tags',
        ),
        migrations.AddField(
            model_name='diary',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default=django.utils.timezone.get_current_timezone_name),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_ingredients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='diary',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='diary_entries', to='diary.ingredient'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_ingredient_per_user'),
        ),
    ]
