# Generated by Django 5.1.8 on 2025-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_diary_tags_diary_timezone_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='timezone',
        ),
        migrations.AddField(
            model_name='diary',
            name='category',
            field=models.CharField(choices=[('eat', 'Eat'), ('drink', 'Drink'), ('exercise', 'Exercise')], default='eat', max_length=10),
        ),
    ]
